server.port=8071
spring.application.name=gateway-server

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Spring Cloud Gateway routing config
spring.cloud.gateway.routes[0].id=identity-service
spring.cloud.gateway.routes[0].uri=lb://identity-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**,/api/admin/**,/api/teacher/**,/api/student/**,/api/parent/**,/api/teachers/**,/api/students/**

spring.cloud.gateway.routes[1].id=school-service
spring.cloud.gateway.routes[1].uri=lb://school-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/schools/**,/api/classes/**

spring.cloud.gateway.routes[2].id=simulation-service
spring.cloud.gateway.routes[2].uri=lb://simulation-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/simulations/**,/api/assignments/**,/api/assessments/**

# Global CORS configurations (allows frontend access)
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
